version: '2.1'
#networks:
#  drugstore:
#    name: drugstore
#    driver: bridge
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.6.6-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
#    networks: [ drugstore ]
#  db_order:
#    container_name: db_order
#    image: mysql:8.0.26
#    restart: on-failure
#    environment:
#      MYSQL_ROOT_PASSWORD: admin
#      MYSQL_DATABASE: db_order
#      MYSQL_USER: admin
#      MYSQL_PASSWORD: admin
#    ports: [ "13017:3306" ]
#  order-service:
#    container_name: order
#    image: drugstore/order-service
#    restart: on-failure
#    build:
#      context: ../order/order-service/
#      dockerfile: ./Dockerfile
#    ports: [ '8082:8082' ]
#    networks: [ drugstore ]
#    depends_on: [ db_order ]
